spring:
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration
  h2:
    console:
      enabled: false

server:
  port: ${PORT:8080}

app:
  users:
    admin:
      username: ${APP_ADMIN_USERNAME}
      password: ${APP_ADMIN_PASSWORD}
    kaio:
      username: ${APP_KAIO_USERNAME}
      password: ${APP_KAIO_PASSWORD}
