spring:
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration
  thymeleaf:
    cache: true
  h2:
    console:
      enabled: false

  security:
    user:
      name: ${APP_USER:delrey}
      password: ${APP_PASSWORD}

server:
  port: ${PORT:8080}
