CREATE TABLE carro (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    modelo VARCHAR(100) NOT NULL,
    ano INT NOT NULL,
    motor VARCHAR(50),
    versao VARCHAR(50),
    placa VARCHAR(10),
    km_atual INT NOT NULL DEFAULT 0,
    observacoes TEXT
);

CREATE TABLE categoria_peca (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(80) NOT NULL UNIQUE
);

CREATE TABLE peca (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(150) NOT NULL,
    categoria_id BIGINT NOT NULL,
    codigo_oem VARCHAR(60),
    fabricante VARCHAR(80),
    intervalo_km INT,
    intervalo_meses INT,
    observacoes TEXT,
    CONSTRAINT fk_peca_categoria FOREIGN KEY (categoria_id) REFERENCES categoria_peca(id)
);

CREATE INDEX idx_peca_nome ON peca(nome);
CREATE INDEX idx_peca_categoria ON peca(categoria_id);

CREATE TABLE troca (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    carro_id BIGINT NOT NULL,
    peca_id BIGINT NOT NULL,
    data_troca DATE NOT NULL,
    km INT NOT NULL,
    valor DECIMAL(10,2) NOT NULL,
    fornecedor VARCHAR(120),
    garantia_meses INT,
    mao_de_obra DECIMAL(10,2),
    observacoes TEXT,
    CONSTRAINT fk_troca_carro FOREIGN KEY (carro_id) REFERENCES carro(id),
    CONSTRAINT fk_troca_peca FOREIGN KEY (peca_id) REFERENCES peca(id)
);

CREATE INDEX idx_troca_data ON troca(data_troca);
CREATE INDEX idx_troca_peca ON troca(peca_id);

CREATE TABLE anexo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    troca_id BIGINT NOT NULL,
    tipo VARCHAR(30) NOT NULL,
    nome_arquivo VARCHAR(255) NOT NULL,
    caminho VARCHAR(500) NOT NULL,
    descricao VARCHAR(255),
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_anexo_troca FOREIGN KEY (troca_id) REFERENCES troca(id) ON DELETE CASCADE
);

CREATE TABLE problema (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    carro_id BIGINT NOT NULL,
    titulo VARCHAR(150) NOT NULL,
    sintoma TEXT NOT NULL,
    data_inicio DATE NOT NULL,
    data_resolucao DATE,
    troca_id_resolveu BIGINT,
    observacoes TEXT,
    CONSTRAINT fk_problema_carro FOREIGN KEY (carro_id) REFERENCES carro(id),
    CONSTRAINT fk_problema_troca FOREIGN KEY (troca_id_resolveu) REFERENCES troca(id)
);

CREATE TABLE problema_peca_suspeita (
    problema_id BIGINT NOT NULL,
    peca_id BIGINT NOT NULL,
    PRIMARY KEY (problema_id, peca_id),
    CONSTRAINT fk_pps_problema FOREIGN KEY (problema_id) REFERENCES problema(id) ON DELETE CASCADE,
    CONSTRAINT fk_pps_peca FOREIGN KEY (peca_id) REFERENCES peca(id)
);
