-- Hodômetro: leituras periódicas do km
CREATE TABLE leitura_km (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    carro_id BIGINT NOT NULL,
    data DATE NOT NULL,
    km INT NOT NULL,
    observacoes TEXT,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_leitura_carro FOREIGN KEY (carro_id) REFERENCES carro(id)
);

CREATE INDEX idx_leitura_data ON leitura_km(data);

-- Abastecimentos
CREATE TABLE abastecimento (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    carro_id BIGINT NOT NULL,
    data DATE NOT NULL,
    km INT,
    litros DECIMAL(10,3) NOT NULL,
    valor_litro DECIMAL(10,3) NOT NULL,
    valor_total DECIMAL(10,2) NOT NULL,
    tipo_combustivel VARCHAR(20),
    posto VARCHAR(120),
    tanque_cheio BOOLEAN NOT NULL DEFAULT TRUE,
    observacoes TEXT,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_abast_carro FOREIGN KEY (carro_id) REFERENCES carro(id)
);

CREATE INDEX idx_abast_data ON abastecimento(data);
